# Generated by Django 5.1.7 on 2025-04-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_groups', to='products.category')),
            ],
            options={
                'verbose_name': 'Size Group',
                'verbose_name_plural': 'Size Groups',
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
