# Generated by Django 5.1.7 on 2025-04-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sizegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('size_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.sizegroup')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['size_group', 'name'], name='size_group_size_group_idx')],
                'unique_together': {('size_group', 'name')},
            },
        ),
    ]
