# Generated by Django 5.1.7 on 2025-04-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_price_productitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender_name',
            new_name='name',
        ),
    ]
