# Generated by Django 5.1.7 on 2025-04-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_gender_name_gender_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizegroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='size_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='size_group_categories', to='products.gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.gender'),
        ),
        migrations.RemoveField(
            model_name='sizegroup',
            name='category',
        ),
    ]
