# Generated by Django 5.1.7 on 2025-04-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_sizegroup_unique_together_category_size_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_group_categories', to='products.sizegroup'),
        ),
    ]
