# Generated by Django 5.1.7 on 2025-04-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_size_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.AlterField(
            model_name='category',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_group_categories', to='products.sizegroup'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
