# Generated by Django 5.1.7 on 2025-04-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_color_hex_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['product__name'], 'verbose_name': 'Product Item', 'verbose_name_plural': 'Product Items'},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
    ]
