# Generated by Django 5.1.7 on 2025-04-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productitem_options_remove_productitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
