# Generated by Django 5.1.7 on 2025-06-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.CharField(default='none', max_length=128, unique=False),
            preserve_default=False,
        ),
    ]
