# Generated by Django 5.1.7 on 2025-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
